# Generated by Django 5.1.1 on 2024-09-23 19:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='user_id')),
                ('password', models.CharField(max_length=128)),
                ('customer_name', models.CharField(max_length=10, verbose_name='name')),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女'), ('不願透漏', '不願透漏')], max_length=5)),
                ('birthday', models.CharField(max_length=7)),
                ('line_id', models.CharField(blank=True, max_length=45, null=True)),
                ('last_login', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User',
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HerbStock',
            fields=[
                ('herbs_id', models.IntegerField(primary_key=True, serialize=False)),
                ('herbs_name', models.CharField(max_length=10)),
                ('current_stock', models.FloatField()),
            ],
            options={
                'db_table': 'herb_stock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchases_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('herbs_id', models.IntegerField()),
                ('supply_id', models.CharField(max_length=45)),
                ('herbs_name', models.CharField(max_length=10)),
                ('purchases_value', models.FloatField()),
                ('purchases_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'purchase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(max_length=15)),
                ('product_name', models.CharField(max_length=10)),
                ('herbs_id', models.IntegerField()),
                ('herbs_name', models.CharField(max_length=10)),
                ('sales_value', models.FloatField()),
                ('order_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'sale',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShowResult',
            fields=[
                ('show_id', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'show_result',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DailyCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('counter', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'dailycounter',
            },
        ),
        migrations.CreateModel(
            name='TongueColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=255)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tonguecolor',
            },
        ),
        migrations.CreateModel(
            name='SymptomOfQuestion',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='symptom_questions', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('question_time', models.DateTimeField()),
                ('q1', models.IntegerField(blank=True, db_column='Q1', null=True)),
                ('q2', models.IntegerField(blank=True, db_column='Q2', null=True)),
                ('q3', models.IntegerField(blank=True, db_column='Q3', null=True)),
                ('q4', models.IntegerField(blank=True, db_column='Q4', null=True)),
                ('q5', models.IntegerField(blank=True, db_column='Q5', null=True)),
                ('q6', models.IntegerField(blank=True, db_column='Q6', null=True)),
            ],
            options={
                'db_table': 'symptom of question',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sale2',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.sale')),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'sale_2',
                'managed': False,
            },
        ),
    ]
