# Generated by Django 3.2.3 on 2024-04-08 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('account', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('herbs_id', models.IntegerField()),
                ('sales_value', models.FloatField()),
                ('order_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'sale',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HerbsStock',
            fields=[
                ('herbs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.sale')),
                ('herbs_name', models.CharField(max_length=45)),
                ('current_stock', models.FloatField()),
            ],
            options={
                'db_table': 'herbs_stock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sale2',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.sale')),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'sale_2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SymptomOfQuestion',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='symptom_questions', serialize=False, to='myapp.sale')),
                ('q1', models.IntegerField(blank=True, db_column='Q1', null=True)),
                ('q2', models.IntegerField(blank=True, db_column='Q2', null=True)),
                ('q3', models.IntegerField(blank=True, db_column='Q3', null=True)),
                ('q4', models.IntegerField(blank=True, db_column='Q4', null=True)),
                ('q5', models.IntegerField(blank=True, db_column='Q5', null=True)),
                ('q6', models.IntegerField(blank=True, db_column='Q6', null=True)),
            ],
            options={
                'db_table': 'symptom of question',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='customers', serialize=False, to='myapp.symptomofquestion')),
                ('password', models.CharField(max_length=45)),
                ('customer_name', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('line_id', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('purchases', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.herbsstock')),
                ('purchases_value', models.IntegerField()),
                ('purchases_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'purchases',
                'managed': False,
            },
        ),
    ]
