# Generated by Django 5.1.1 on 2024-09-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tonguecolor',
            name='customer_id',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
