# Generated by Django 3.2.3 on 2024-04-08 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchases',
            options={'managed': True},
        ),
    ]
