# Generated by Django 3.2.3 on 2024-04-08 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_purchases_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchases',
            options={'managed': False},
        ),
    ]
