# Generated by Django 3.2.12 on 2024-05-06 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_purchases_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchases_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('herbs_id', models.IntegerField()),
                ('herbs_name', models.CharField(max_length=10)),
                ('purchases_value', models.FloatField()),
                ('purchases_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'purchase',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='purchases',
        ),
        migrations.CreateModel(
            name='HerbStock',
            fields=[
                ('herbs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.purchase')),
                ('herbs_name', models.CharField(max_length=10)),
                ('current_stock', models.FloatField()),
            ],
            options={
                'db_table': 'herb_stock',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='HerbsStock',
        ),
        migrations.DeleteModel(
            name='Purchases',
        ),
    ]
