# Generated by Django 3.2.3 on 2024-05-13 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20240506_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': False, 'verbose_name': 'User'},
        ),
    ]
