# Generated by Django 3.2.3 on 2024-05-13 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': True, 'verbose_name': 'User'},
        ),
    ]
