# Generated by Django 3.2.3 on 2024-05-13 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': False, 'verbose_name': 'User'},
        ),
    ]
