# Generated by Django 3.2.12 on 2024-05-17 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_customer_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
